inventory-management/Models/ErrorViewModel.cs
using System;

namespace inventory_management.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

inventory-management/Models/inventory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace InventoryManagement.Models{

public class Inventory{
    public int Id { get;set;}
    
    public string Name { get;set;}
    public string Supplier { get; set;}
    public DateTime ExpDate { get; set;}
    public float Price { get; set;}
    public int Quantity {get; set;}
    
     public static List<Inventory> GetInventory()
     {
            Inventory inventory1 = new Inventory()
            {

            };
            Inventory inventory2 = new Inventory()
            {

            };
            List<Inventory> inventories =new List<Inventory>(){inventory1,inventory2};
            return inventories;
     }
}
public class Users
{
      [Required]
       public int Id{get; set;}
       [Required]
       public string firstname{get; set;}
       [Required]
       public string lastname{get; set;}
       [Required]
        [Key]
       public string username {get; set;}
       [Required]
       public string password{get; set;}
       [Required]
       public decimal mobile {get; set;}
       [Required]

       public string email {get; set;}
       [Required]
       public string role {get; set;}


}
}

inventory-management/Controllers/InventoryController.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

using InventoryManagement.Models;
using InventoryManagement.Data;
using System.Threading.Tasks;
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;

namespace InventoryManagement.Controllers{
    public class InventoryController: Controller{
        private readonly IMSContext db;
        public InventoryController(IMSContext _db)
        {
            db = _db;
        }
        [Authorize]
        public IActionResult WelcomePage()
        {
            return View();
        }
        [Authorize]
        public IActionResult Index()
        {   
            var product = db.Inventories.ToList();
            return View(product);
        }
      
        public IActionResult lessquantity()
        {   
            var product = db.Inventories.ToList();
            return View(product);
        }


        [Authorize(Roles= "Admin")]
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Inventory inventoy)
        {
            db.Inventories.Add(inventoy);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var abcd = db.Inventories.Find(Id);
            return View(abcd);
        }


        [HttpPost]
        public ActionResult Edit(Inventory inventory)
        {
            db.Inventories.Attach(inventory);
            db.Inventories.Update(inventory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var abcde = db.Inventories.Find(Id);
            return View(abcde);
        }


        [HttpPost]
        public ActionResult Delete(Inventory inventory)
        {
            db.Inventories.Attach(inventory);
            db.Inventories.Remove(inventory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Sell(int Id)
        {
            var abcdef = db.Inventories.Find(Id);
            return View(abcdef);
        }


        [HttpPost]
        public ActionResult Sell(Inventory inventory)
        {
            db.Inventories.Attach(inventory);
            db.Inventories.Update(inventory);
            db.SaveChanges();
            return RedirectToAction("Index");
        }    

        public async Task<IActionResult> Search(string searchString)
        {
            var goods = from m in db.Inventories
                        select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                goods = goods.Where(s => s.Name.Contains(searchString));
            }

            return View(await goods.ToListAsync());
        }

        public async Task<IActionResult> expired()
        {
            var expgoods = from m in db.Inventories
                        select m;

            DateTime today = DateTime.Now; // 12/20/2015 11:48:09 AM  
            DateTime newDate2 = today.AddDays(30); // Adding one month(as 30 days)  
            
            expgoods = expgoods.Where(s => s.ExpDate < newDate2); 

            return View(await expgoods.ToListAsync());
        }


        // authentication through login

        [HttpGet("login")]

        public IActionResult Login(string ReturnUrl)
        {
            ViewData["returnUrl"]= ReturnUrl;
            
            return View();
        }

        
        [HttpPost("login")]
        public async Task<IActionResult> Validatelogin(string username, string password,string ReturnUrl)
        {   ViewData["returnUrl"]= ReturnUrl;
        var check = db.Usertable.Find(username);
        if(check!=null)
        {
            var passwordcheck=check.password;
            if( password==passwordcheck)
            {
                var fullname=check.firstname+" "+check.lastname;
            
                  // giving the login credential througn claims authentication
                var claims = new List<Claim>();
                claims.Add(new Claim("username",username));
                claims.Add(new Claim(ClaimTypes.NameIdentifier,username));
                claims.Add(new Claim(ClaimTypes.Name,fullname));
                claims.Add(new Claim(ClaimTypes.Role,check.role));
                
                var claimsIdentity = new ClaimsIdentity(claims,CookieAuthenticationDefaults.AuthenticationScheme);
                var claimsPrincipal = new ClaimsPrincipal(claimsIdentity);
                await HttpContext.SignInAsync(claimsPrincipal);
                return Redirect(ReturnUrl);
            }
            TempData["Error"] ="Error. Username or Password Error";
            return View("login");

        }
        
            
            TempData["Error"] ="Error. Username or Password Error";
            return View("login");
            
        }
        [Authorize]
        public IActionResult auth()
        {
            return View("WelcomePage");
        }
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return Redirect("/");
        }
        [HttpGet("denied")]
        public IActionResult Denied()
        {
            return View();
        }
       [HttpGet]
        public IActionResult Register()
        {      
                 return View();      
        }
          [HttpPost]
        public ActionResult Register(Users users,string username,string email)
        {
            var check = db.Usertable.Find(username);
            
             if(check==null)
             {
                 db.Usertable.Add(users);
            db.SaveChanges();
            return RedirectToAction("Index");
             }
              TempData["Error"] ="User name already exist";
            return View("Register");
            
            
        }

        public IActionResult UserList()
        {
            var userlist = db.Usertable.ToList();
            return View(userlist);
        }

         [HttpGet]
        public ActionResult userdelete(string username)
        {
            var abcde = db.Usertable.Find(username);
            return View(abcde);
        }


        [HttpPost]
        public ActionResult userdelete(Users user)
        {
            db.Usertable.Attach(user);
            db.Usertable.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

inventory-management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inventory Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header >
        <nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark ">
            <a class="navbar-brand" asp-area="" asp-controller="Inventory" asp-action="WelcomePage" style="font-family:Arial;">Inventory
                Management</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse display-4" id="navbarSupportedContent" >
                <ul class="navbar-nav mr-auto navbar-brand">
                    @if (User.IsInRole("Admin") || User.IsInRole("Seller") || User.IsInRole("Viewer"))
                    {
                        <li class="nav-item pl-3">
                            <a class="nav-link" asp-area="" asp-controller="Inventory" asp-action="Index">Home
                                <span class="sr-only">(current)</span></a>
                        </li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item pl-3">
                            <a class="nav-link" asp-area="" asp-controller="Inventory" asp-action="Create">Add
                                <span class="sr-only">(current)</span></a>
                        </li>
                    }
                    @if (User.IsInRole("Admin") || User.IsInRole("Seller") || User.IsInRole("Viewer"))
                    {
                        <li class="nav-item pl-3">
                            <a class="nav-link" asp-area="" asp-controller="Inventory" asp-action="lessquantity">Less
                                Quantity<span class="sr-only">(current)</span></a>
                        </li>
                        <li class="nav-item pl-3">
                            <a class="nav-link" asp-area="" asp-controller="Inventory" asp-action="expired">Expiring
                                Items<span class="sr-only">(current)</span></a>
                        </li>
                    }
                    @if (User.IsInRole("Admin"))
                    {
                        <li class="nav-item pl-3">
                            <a class="nav-link" asp-area="" asp-controller="Inventory" asp-action="UserList">UserList<span
                                    class="sr-only">(current)</span></a>
                        </li>
                    }
                </ul>
                @if (User.Identity.IsAuthenticated)
                {
                    <nav class="navbar navbar-light bg-light navbar-dark bg-dark">
                        <form class="form-inline" asp-controller="Inventory" asp-action="Search">
                            <input class="form-control mr-sm-2" type="search" name="SearchString" placeholder="Search"
                                aria-label="Search">
                            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                        </form>
                        <form class="form-inline" asp-area="" asp-controller="Inventory" asp-action="Logout">
                            <button class="btn btn-outline-success " type="submit">Logout</button>
                        </form>
                    </nav>
                }
            </div>
        </nav>
    </header>
    <div class="container-fluid ">
        <div class="container ">
            <main role="main" class="pb-3 ">
                @RenderBody()
            </main>
        </div>
    </div>
    <footer class="border-top footer text-muted navbar-dark bg-dark">
        <div class="container">
            &copy; 2021 - Inventory Management System
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>

</html>

inventory-management/Views/inventory/Denied.cshtml
<h1 style="font-family: Arial, sans-serif;">This page is only accessied by the ADMIN</h1>

inventory-management/Views/inventory/Index.cshtml
@model List<Inventory>;
@{
  Layout = "_Layout";
}
@{
  ViewData["Title"] = "Inventory List";
}
<br>
<div style="font-family: Arial, sans-serif;" class="h2 text-muted">
  List of Inventories
</div>
<table class="table table-striped table-hover table-bordered table-secondary">

  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Supplier</th>
      <th scope="col">Expiry Date</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      @if (User.IsInRole("Admin"))
      {
        <th scope="col">Action</th>
      }
      @if (User.IsInRole("Seller"))
      {
        <th scope="col">Sold</th>
      }

    </tr>
  </thead>
  @foreach (var inventory in Model)
  {
    <tbody>
      <tr>
        <th scope="row">@inventory.Id</th>
        <td>@inventory.Name</td>
        <td>@inventory.Supplier</td>
        <td>@inventory.ExpDate</td>
        <td>@inventory.Price</td>
        <td>@inventory.Quantity</td>
        @if (User.IsInRole("Admin"))
        {
          <td>
            <a class="btn btn-warning" href="/inventory/edit?id=@inventory.Id">
              Edit
            </a>
            <a class="btn btn-danger" href="/inventory/delete?id=@inventory.Id">
              Delete
            </a>
          </td>
        }
        @if (User.IsInRole("Seller"))
        {
          <td><a class="btn btn-success" href="/inventory/sell?id=@inventory.Id">Sell</td>
        }

      </tr>
    </tbody>
  }
</table>

inventory-management/Views/inventory/Login.cshtml
@{
    var ReturnUrl = ViewData["returnUrl"] as string;
    var error = TempData["Error"] as string;
}


@if (!string.IsNullOrEmpty(error))
{
    <h4 style="font-family: Arial, sans-serif;" class="alert-danger" style="padding: 20px;">@error</h4>
}
<div>
    <form class="px-4 py-3" action="/login?ReturnUrl=@System.Net.WebUtility.UrlEncode(ReturnUrl)" method="POST">
    <label style="font-family: Arial, sans-serif;" class="text-danger h5">REGISTERED CUSTOMERS</label>
    <p style="font-family: Arial, sans-serif;">If you have an account with us, please log in.</p>
        <div class="form-group">
            <label>User Name</label>
            <input type="text" class="form-control" name="username">
        </div>
        <div class="form-group">
            <label>Password</label>
            <input type="password" class="form-control" name="password">
        </div>
        <div class="form-group">
            <div class="form-check">
                <input type="checkbox" class="form-check-input" id="dropdownCheck">
                <label class="form-check-label" for="dropdownCheck">
                    Remember me
                </label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">Sign in</button>
    </form>
    <Span>New around here?</span>
    <a asp-area="" asp-controller="Inventory" asp-action="Register">Sign up</a>
</div>

inventory-management/Views/inventory/Register.cshtml
@{
  var error = TempData["Error"] as string;
}
@model Users
@if (!string.IsNullOrEmpty(error))
{
  <h2 class="alert-danger" style="padding: 20px;">@error</h2>
}
<br>
<div style="font-family: Arial, sans-serif;" class=" text-danger h4">Register your Account</div>
<form class="border border-secondary" action="/inventory/Register" method="POST">
  <div class="card-body">
    <div class="col-md-6 form-group">
      <label asp-for="firstname">First Name</label>
      <span asp-validation-for="firstname" class="text-danger"></span>
      <input asp-for="firstname" class="form-control" type="text" required>
    </div>
    <div class="col-md-6 form-group">
      <label asp-for="lastname"> Last Name</label>
      <span asp-validation-for="lastname" class="text-danger"></span>
      <input asp-for="lastname" class="form-control" type="text" required>
    </div>
    <div class="col-md-6 form-group">
      <label asp-for="username"> Username</label>
      <span asp-validation-for="username" class="text-danger"></span>
      <input asp-for="username" class="form-control" type="text" required>
    </div>
    <div class="col-md-6 form-group">
      <label asp-for="password"> Password</label>
      <span asp-validation-for="password" class="text-danger"></span>
      <input asp-for="password" class="form-control" type="password" required>
    </div>
    <div class="col-md-6 form-group">
      <label asp-for="mobile"> Mobile</label>
      <span asp-validation-for="mobile" class="text-danger"></span>
      <input asp-for="mobile" class="form-control" type="number" required>
    </div>
    <div class="col-md-6 form-group">
      <label asp-for="email"> Email</label>
      <span asp-validation-for="email" class="text-danger"></span>
      <input asp-for="email" class="form-control" type="text" required>
    </div>
    <div class="col-md-6 form-group">
      <label asp-for="role"> Role</label>
      <span asp-validation-for="role" class="text-danger"></span>

      <select asp-for="role" class="form-control">
        <option value="Admin">Admin</option>
        <option value="Seller">Seller</option>
        <option value="Viewer">Viewer</option>
      </select>
    </div>
  </div>
  <div class="card-footer">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>

inventory-management/Views/inventory/UserList.cshtml
@model List<Users>;
@{
  Layout = "_Layout";
}

@{
  ViewData["Title"] = "User List";
}

<br>
<div style="font-family: Arial, sans-serif;" class="h2 text-muted">
  List of Users
</div>
<table class="table table-striped table-hover table-bordered table-secondary">
  <thead class="thead-dark">
    <tr>

      <th scope="col">Full Name</th>
      <th scope="col">Username</th>
      <th scope="col">Mobile</th>
      <th scope="col">Email</th>
      <th scope="col">Role</th>
      @if (User.Identity.IsAuthenticated)
      {
        <th scope="col">Action</th>
      }

    </tr>
  </thead>
  @foreach (var user in Model)
  {
    <tbody>
      <tr>

        <td>@user.firstname @user.lastname</td>
        <td>@user.username</td>
        <td>@user.mobile</td>
        <td>@user.email</td>
        <td>@user.role</td>
        @if (User.Identity.IsAuthenticated)
        {
          <td>
            <a class="btn btn-danger" href="/inventory/userdelete?username=@user.username">Delete</a>
          </td>
        }
      </tr>
    </tbody>
  }
</table>

inventory-management/Views/inventory/WelcomePage.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center mt-5 pt-5 display-4 text-muted" style="font-family: Helvetica, sans-serif;">
    <label>Welcome To Inventory Management System</label> @User.Identity.Name
</div>

inventory-management/Views/inventory/create.cshtml
@model Inventory
<br>
<div style="font-family: Arial, sans-serif;" class="h2 text-muted">
  Create inventory
</div>
<form class="border border-secondary" action="/inventory/Create" method="POST">
  <form>

    <div class="card-body">
      <div class="col-md-6 form-group">
        <label asp-for="Name">Name</label>
        <span asp-validation-for="Name" class="text-danger"></span>
        <input asp-for="Name" class="form-control" type="text" required>
      </div>
      <div class="col-md-6 form-group">
        <label asp-for="Supplier"> Supplier</label>
        <span asp-validation-for="Supplier" class="text-danger"></span>
        <input asp-for="Supplier" class="form-control" type="text" required>
      </div>
      <div class="col-md-6 form-group">
        <label asp-for="ExpDate"> Expiry Date</label>
        <span asp-validation-for="ExpDate" class="text-danger"></span>
        <input asp-for="ExpDate" class="form-control" type="date" required>
      </div>
      <div class="col-md-6 form-group">
        <label asp-for="Price"> Price</label>
        <span asp-validation-for="Price" class="text-danger"></span>
        <input asp-for="Price" class="form-control" type="number" required>
      </div>
      <div class="col-md-6 form-group">
        <label asp-for="Quantity"> Quantity</label>
        <span asp-validation-for="Quantity" class="text-danger"></span>
        <input asp-for="Quantity" class="form-control" type="number" required>
      </div>
    </div>
    <div class="card-footer">
      <button type="submit" class="btn btn-primary">Submit</button>
    </div>
  </form>
  </div>
</form>
<!-- /.card -->

inventory-management/Views/inventory/delete.cshtml
@model Inventory
<form action="/inventory/delete" method="POST">
    <input type="hidden" asp-for="Id" />
        <h3>Do you want to delete this record? </h3>
        <br>
        <button type="submit" class="btn btn-primary">Delete</button>
</form>

inventory-management/Views/inventory/edit.cshtml
@model Inventory
<br>
<div style="font-family: Arial, sans-serif;" class="h2 text-muted ">
  Edit inventory
</div>
<form  class="border border-secondary" action="/inventory/edit" method="POST">
    <input type="hidden" asp-for="Id" />
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-8">
              <form>
                <div class="card-body">
                    <div class="col-md-6 form-group">
                    <label asp-for="Name">Name</label>
                    <span asp-validation-for="Name" class="text-danger"></span>
                          <input asp-for="Name" class="form-control" type="text" required>      
                    </div>
                    <div class="col-md-6 form-group">
                    <label asp-for="Supplier"> Supplier</label>
                    <span asp-validation-for="Supplier" class="text-danger"></span>
                          <input asp-for="Supplier" class="form-control" type="text" required>      
                  </div>
                  <div class="col-md-6 form-group">
                    <label asp-for="ExpDate"> Expiry Date</label>
                    <span asp-validation-for="ExpDate" class="text-danger"></span>
                          <input asp-for="ExpDate" class="form-control" type="date" required>      
                  </div>
                  <div class="col-md-6 form-group">
                    <label asp-for="Price"> Price</label>
                    <span asp-validation-for="Price" class="text-danger"></span>
                          <input asp-for= "Price" class="form-control" type="number" required>      
                  </div>
                  <div class="col-md-6 form-group">
                    <label asp-for="Quantity"> Quantity</label>
                    <span asp-validation-for="Quantity" class="text-danger"></span>
                          <input asp-for= "Quantity" class="form-control" type="number" required>      
                  </div>
                </div>
                <div class="card-footer">
                  <button type="submit" class="btn btn-primary">Update</button>
                </div>
              </form>
            </div>
</form>            
            <!-- /.card -->

inventory-management/Views/inventory/expired.cshtml
@model List<Inventory>;
  @{
    Layout = "_Layout";
  }
  @{
    ViewData["Title"] = "Inventory List (expire)";
}


<br>
<div style="font-family: Arial, sans-serif;" class="h2 text-muted">
 List of Inventories that are going to expire in 1 month
</div>

    <table class="table table-striped table-hover table-bordered table-secondary">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Supplier</th>
      <th scope="col">Expiry Date</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
         @if(User.IsInRole("Admin"))
      {
        <th scope="col">Action</th>
        }
        @if(User.IsInRole("Seller"))
        {
          <th scope="col">Sold</th>
        }
      
     
    </tr>
  </thead>
 

@foreach (var inventory in Model)
{
    
    {
        <tbody>
            <tr>
            <th scope="row">@inventory.Id</th>
            <td>@inventory.Name</td>
            <td>@inventory.Supplier</td>
            <td>@inventory.ExpDate</td>
            <td>@inventory.Price</td>
            <td>@inventory.Quantity</td>
       @if(User.IsInRole("Admin"))
      {
         <td>
            <a class="btn btn-warning" href="/inventory/edit?id=@inventory.Id">
              Edit
            </a>
            <a class="btn btn-danger" href="/inventory/delete?id=@inventory.Id">
              Delete
            </a>
          </td>
      }  
      @if(User.IsInRole("Seller"))
      {
        <td><a class="btn btn-success" href="/inventory/sell?id=@inventory.Id">Sell</td>
      }
            </tr>
        </tbody>
    }

}
</table>

inventory-management/Views/inventory/lessquantity.cshtml
@model List<Inventory>;
  @{
    Layout = "_Layout";
  }
  @{
    ViewData["Title"] = "Inventories that are less than 50";
}
<br>
<div style="font-family: Arial, sans-serif;" class="h2 text-muted">
  List of Inventories that are less than 50
</div>
    <table class="table table-striped table-hover table-bordered table-secondary">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Supplier</th>
      <th scope="col">Expiry Date</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
      @if(User.IsInRole("Admin"))
      {
        <th scope="col">Action</th>
        }
        @if(User.IsInRole("Seller"))
        {
          <th scope="col">Sold</th>
        }
    </tr>
  </thead>
@foreach (var inventory in Model)
{
    if(@inventory.Quantity < 50)
    {
           <tbody>
            <tr>
            <th scope="row">@inventory.Id</th>
            <td>@inventory.Name</td>
            <td>@inventory.Supplier</td>
            <td>@inventory.ExpDate</td>
            <td>@inventory.Price</td>
            <td>@inventory.Quantity</td>
                @if(User.Identity.IsAuthenticated)
       @if(User.IsInRole("Admin"))
      {
        <td>
            <a class="btn btn-warning" href="/inventory/edit?id=@inventory.Id">
              Edit
            </a>
            <a class="btn btn-danger" href="/inventory/delete?id=@inventory.Id">
              Delete
            </a>
          </td>
      }  
      @if(User.IsInRole("Seller"))
      {
        <td><a class="btn btn-success" href="/inventory/sell?id=@inventory.Id">Sell</td>
      }          
    </tr>
  </tbody>
    }

}
</table>

inventory-management/Views/inventory/search.cshtml
@model List<Inventory>;
  @{
    Layout = "_Layout";
  }
  @{
    ViewData["Title"] = "Searched List";
}
<div style="font-family: Arial, sans-serif;" class="h2 text-muted ">
  Inventories:
</div>
    <table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Supplier</th>
      <th scope="col">Expiry Date</th>
      <th scope="col">Price</th>
      <th scope="col">Quantity</th>
       @if(User.IsInRole("Admin"))
      {
        <th scope="col">Action</th>
        }
        @if(User.IsInRole("Seller"))
        {
          <th scope="col">Sold</th>
        }
    </tr>
  </thead>
@foreach (var inventory in Model)
{
   <tbody>
    <tr>
      <th scope="row">@inventory.Id</th>
      <td>@inventory.Name</td>
      <td>@inventory.Supplier</td>
      <td>@inventory.ExpDate</td>
      <td>@inventory.Price</td>
      <td>@inventory.Quantity</td>
          @if(User.IsInRole("Admin"))
      {
          <td>
            <a class="btn btn-warning" href="/inventory/edit?id=@inventory.Id">
              Edit
            </a>
            <a class="btn btn-danger" href="/inventory/delete?id=@inventory.Id">
              Delete
            </a>
          </td>
      
      }  
      @if(User.IsInRole("Seller"))
      {
        <td><a href="/inventory/sell?id=@inventory.Id">Sell</td>
      }
    </tr>
  </tbody>
}
</table>

inventory-management/Views/inventory/sell.cshtml
@model Inventory
<form action="/inventory/sell" method="POST">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="Name" />
    <input type="hidden" asp-for="Supplier" />
    <input type="hidden" asp-for="ExpDate" />
    <input type="hidden" asp-for="Price" />
    <div class="col-md-6 form-group">
        <label style="font-family: Arial, sans-serif;" class="h3 text-muted">How many item do you want to sell?</label>
        <input id="sell" type="number" class="form-control" required>
        <input id="original" type="hidden" asp-for="Quantity" class="form-control" required>
        <script>
            function myFunction() {
                var sellquant = Number(document.getElementById("sell").value);
                var originalquan = Number(document.getElementById("original").value);
                var rem = Number(originalquan - sellquant);
                if (rem >= 0) {
                    document.getElementById("original").value = rem;
                }
                else {
                    alert("The quantity you have entered is more than the quantity the inventory has.");
                }

            }
        </script>
        <br>
        <button type="submit" onclick="myFunction()" class="btn btn-success">Sell the quantity</button>
    </div>
</form>

inventory-management/Views/inventory/userdelete.cshtml
@model Users
<form action="/inventory/userdelete" method="POST">
    <input type="hidden" asp-for="username" />

         <label style="font-family: Arial, sans-serif;" class="h3 text-muted">Do you want to delete this record?</label>
        <br>
        <button type="submit" class="btn btn-danger">Delete</button>
</form>